common/models/Order.php
<?php

/**
 * Sales Orders
 * @author Demid [Alexander Pilipenko] <webdemid@gmail.com>
 * @since 1.0
 */

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

/**
 * Database structure
 *
 * @property int(11)      $id               - Unique identificator
 */
class Order extends \common\ext\db\ActiveRecord
{
    /**
     * Order statuses
     */
    const STATUS_ACCEPTED = 0;
    const STATUS_PENDING = 1;
    const STATUS_SUCCESS = 2;
    const STATUS_FAIL = 3;
    const STATUS_CANCEL = 4;

    /**
     * Payments
     */
    const PAYMENT_TYPE_ROBOKASSA = 1;

    /**
     * Date output format
     */
    const OUT_DATE_FORMAT = 'd.m.Y H:i';

    /**
     * Sorting
     */
    const ORDER_BY_SORTING = 'create_timestamp';

    /**
     * Agreement
     * @var Integer
     */
    public $agreement;

    /**
     * List of statuses
     * @return Array
     */

    public static function getStatusesList()
    {
        return [
            self::STATUS_ACCEPTED => 'Новый заказ',
            self::STATUS_SUCCESS => 'Оплата выполнена',
            self::STATUS_PENDING => 'Ожидание оплаты',
            self::STATUS_FAIL => 'Ошибка при оплате',
            self::STATUS_CANCEL => 'Отмена заказа',
        ];
    }

    /**
     * List of statuses color
     * @return Array
     */
    public static function getStatusesColor()
    {
        return [
            self::STATUS_ACCEPTED => 'bg-slate-300',
            self::STATUS_SUCCESS => 'bg-success-400',
            self::STATUS_PENDING => 'bg-grey-400',
            self::STATUS_FAIL => 'bg-danger',
            self::STATUS_CANCEL => 'bg-danger',
        ];
    }

    /**
     * List of payments
     * @return Array
     */
    public static function getPaymentList()
    {
        return [
            self::PAYMENT_TYPE_ROBOKASSA => 'RoboKassa',
        ];
    }

    /**
     * Status Name
     * @param  Integer $status
     * @return String
     */
    public static function getStatusName($status)
    {
        return ArrayHelper::getValue(static::getStatusesList(), $status, 'Unknown');
    }

    /**
     * Payment Name
     * @param  Integer $payment_type
     * @return String
     */
    public static function getPaymentName($payment_type)
    {
        return ArrayHelper::getValue(static::getPaymentList(), $payment_type, 'Unknown');
    }

    /**
     * Status color
     * @param  Integer $status
     * @return String
     */
    public static function getStatusColor($status)
    {
        return ArrayHelper::getValue(static::getStatusesColor(), $status, 'Unknown');
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%orders}}';
    }

    /**
     * @inheritdoc
     * @return array
     */
    public function rules()
    {
        return [
            ['agreement', 'required', 'on' => 'insert'],
            ['agreement', function ($attribute, $params, $validator) {
                if ($this->$attribute == false) {
                    $this->addError($attribute, 'Вы не приняли условия сайта.');
                }
            }],
            [['user_id', 'create_timestamp', 'paid_timestamp', 'status', 'agreement', 'payment_type'], 'integer'],
            ['cart', 'filter', 'filter' => 'trim'],
            ['cart', 'safe'],
            ['paid_timestamp', 'default', 'value' => 0],
        ];
    }

    /**
     * @inheritdoc
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'agreement' => 'Я принимаю',
            'cart' => 'Корзина',
            'create_timestamp' => 'Время создания заказа',
            'paid_timestamp' => 'Время оплаты заказа',
            'payment_type' => 'Метод оплаты',
            'status' => 'Статус заказа',
            'user_id' => 'Идентификатор пользователя',
        ];
    }

    /**
     * @inheritdoc
     * @return boolean
     */
    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        if ($this->getIsNewRecord()) {
            $this->user_id = Yii::$app->user->identity->id;
            $this->cart = Json::encode(array_keys(Yii::$app->cart->getRecord()));
            $this->create_timestamp = date('U');
            $this->status = self::STATUS_ACCEPTED;

            // Send message for administrator
        }

        return true;
    }

    /**
     * @inheritdoc
     * @return boolean
     */
    public function beforeDelete()
    {
        if (!parent::beforeDelete()) {
            return false;
        }

        // Deleting order data
        OrderData::deleteAll(['item_id' => $this->id]);

        return true;
    }

    /**
     * Order data
     * @return Array
     */
    public function getOrderData()
    {
        return $this->hasMany(OrderData::className(), ['item_id' => 'id']);
    }

    /**
     * User model
     * @return \common\models\User
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * The total amount of the order
     * @return String
     */
    public function getTotalPrice()
    {
        $orderData = $this->orderData;
        $total_price = 0;

        // Total order amount calculation
        if (is_array($orderData)) {
            foreach ($orderData as $item) {
                $total_price = $total_price + ($item->adults * $item->price) + ($item->children * $item->children_price);
            }
        }

        return $total_price;
    }

    /**
     * Counting the total order amount by bp formatting
     * @return String
     */
    public function getTotalPriceFormat()
    {
        return number_format($this->totalPrice, 2, '.', ' ') . ' ' . \common\models\TourPrices::DEFAULT_CURRENCY_NAME;
    }

    /**
     * link to the page
     * @return string
     */
    public function getLinkDetail()
    {
        return '/ordering/detail/' . md5($this->id . $this->create_timestamp);
    }

    public function getLinkPay()
    {
        return '/ordering/pay/' . md5($this->id . $this->create_timestamp);
    }

    public function getLinkCancel()
    {
        return '/ordering/cancel/' . md5($this->id . $this->create_timestamp);
    }
}

frontend/controllers/UsersController.php
<?php

/**
 * User Accounts
 * @author Demid [Alexander Pilipenko] <webdemid@gmail.com>
 * @since 1.1
 */

namespace frontend\controllers;

use common\models\Files;
use common\models\SigninForm;
use common\models\SignupForm;
use common\models\User;
use frontend\models\ChangeEmail;
use frontend\models\ChangeNotification;
use frontend\models\ChangePassword;
use common\models\Order;
use Yii;
use yii\web\Response;
use yii\data\Pagination;

class UsersController extends \frontend\components\FrontendController
{

    public $defaultPageSize = 10; // Number of entries per page

    /**
     * Profile info
     * @return String
     */
    public function actionProfile()
    {
        if(Yii::$app->user->isGuest) {
            return $this->redirect(Yii::$app->user->url->signin);
        }

        $model = User::findOne(Yii::$app->user->identity->id);

        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        if ($model->load(Yii::$app->request->post()) && $model->save(true)) {
            Yii::$app->session->setFlash('success', 'Данные профиля успешно изменены!');
            return $this->redirect(Yii::$app->request->url);
        }

        return $this->render('profile', ['model' => $model]);
    }

    /**
     * Settings account
     * @return String
     */
    public function actionSettings()
    {
        if(Yii::$app->user->isGuest) {
            return $this->redirect(Yii::$app->user->url->signin);
        }

        $model = User::findOne(Yii::$app->user->identity->id);
        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        // Password Updates
        $change_password = new ChangePassword;
        if ($change_password->load(Yii::$app->request->post()) && $change_password->update()) {
            Yii::$app->session->setFlash('success', 'Пароль успешно изменен!');
            return $this->redirect(Yii::$app->request->url);
        }

        // Email Updates
        $change_email = new ChangeEmail;
        if ($change_email->load(Yii::$app->request->post()) && $change_email->update()) {
            Yii::$app->session->setFlash('success', 'Email успешно изменен!');
            return $this->redirect(Yii::$app->request->url);
        }

        // Notification settings
        $change_notification = new ChangeNotification;
        $change_notification->setAttributes([
            'notification_new_tours' => $model->notification_new_tours,
            'notification_comp_news' => $model->notification_comp_news,
        ]);
        unset($model);

        if ($change_notification->load(Yii::$app->request->post()) && $change_notification->update()) {
            Yii::$app->session->setFlash('success', 'Настроки уведомлений успешно обновлены!');
            return $this->redirect(Yii::$app->request->url);
        }

        return $this->render('settings', [
            'change_password' => $change_password,
            'change_email' => $change_email,
            'change_notification' => $change_notification,
        ]);
    }

    /**
     * My orders
     * @return String
     */
    public function actionOrders($sort = null)
    {

        if(Yii::$app->user->isGuest) {
            return $this->redirect(Yii::$app->user->url->signin);
        }

        // Filters
        $filters = [
            'asc' => 'Сначала старые',
            'desc' => 'Сначала новые',
        ];

        // Order by filter
        $order_by = ['id' => SORT_DESC];
        if(isset($_GET['sort']) && $sort !== null) {
            if($sort == 'desc') {
                $order_by = [Order::ORDER_BY_SORTING => SORT_DESC];
            }
            if($sort == 'asc') {
                $order_by = [Order::ORDER_BY_SORTING => SORT_ASC];
            }
        }

        $total = Order::find()
            ->where(['user_id' => Yii::$app->user->identity->id])
            ->andWhere('status != :status', [':status' => Order::STATUS_CANCEL])
            ->orderBy($order_by)
            ->count();

        $pages = new Pagination([
            'totalCount' => $total,
            'pageSize' => $this->defaultPageSize,
        ]);

        $models = Order::find()
            ->where(['user_id' => Yii::$app->user->identity->id])
            ->andWhere('status != :status', [':status' => Order::STATUS_CANCEL])
            ->offset($pages->offset)
            ->limit($pages->limit)
            ->orderBy($order_by)
            ->all();

        return $this->render('orders', [
            'models' => $models,
            'pages' => $pages,
            'filters' => $filters,
            'filter_sort' => $sort
        ]);
    }

    /**
     * Authorization
     * @return String
     */
    public function actionSignin()
    {
        $this->layout = self::LAYOUT_WRAPPER_NAME;
        $model = new SigninForm;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->login();
            return $this->redirect(Yii::$app->user->url->profile);
        }

        return $this->render('signin', ['model' => $model]);
    }

    /**
     * Registration
     * @return String
     */
    public function actionSignup()
    {
        $this->layout = self::LAYOUT_WRAPPER_NAME;
        $model = new SignupForm;

        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            $model->login();
            return $this->redirect(Yii::$app->user->url->profile);
        }

        return $this->render('signup', ['model' => $model]);
    }

    /**
     * Restore password
     * @return String
     */
    public function actionPasswd()
    {
        return $this->render('passwd');
    }

    /**
     * Loading User avatar
     * @return String
     */
    public function actionAvatar()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->isAjax && Yii::$app->request->isPost && !Yii::$app->user->isGuest) {

            $image = new Files(['scenario' => Files::SCENARIO_IMAGE]);
            $user = Yii::$app->user->identity;

            if ($image->load(Yii::$app->request->post())) {
                $image->setRules(Yii::$app->params['upload'][Files::SCENARIO_IMAGE]);

                foreach ($user->files as $item) {
                    $item->delete();
                }

                if ($image->upload()) {
                    return [
                        'link' => $image->getImageLink($user->image_sizes[0]),
                        'item_id' => $image->item_id,
                        'size' => $image->filesize,
                        'id' => $image->id
                    ];
                }
            } else {
                return ['errors' => $image->errors];
            }
        } else {
            return ['access' => 'Access denied'];
        }

        return [];
    }

    /**
     * Exit
     * @return Object
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
}

frontend/views/users/orders.php
<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
?>
<section class="parallax-window" data-parallax="scroll" data-image-src="/img/account_top.jpg" data-natural-width="1400" data-natural-height="470">
    <div class="parallax-content-1">
        <div class="animated fadeInDown">
            <h1>Личный кабинет</h1>
            <p>История заказов</p>
        </div>
    </div>
</section>
<!-- End section -->
<main>
    <div class="margin_60 container">
        <div class="tabs profile-tabs">
            <nav>
                <ul>
                    <li>
                        <a href="<?= Yii::$app->user->url->profile ?>" class="icon-user-5"><span>Информация</span></a>
                    </li>
                    <li class="tab-current">
                        <a href="#orders" onclick="return false;" class="icon-cart"><span>Мои заказы</span></a>
                    </li>
                    <li>
                        <a href="<?= Yii::$app->user->url->settings ?>" class="icon-cog-3"><span>Настройки</span></a>
                    </li>
                </ul>
            </nav>
            <div class="content">
                <section class="content-current">
                <? if(count($models)): ?>
                    <div id="tools">
                        <div class="row">
                            <div class="col-md-3 col-sm-3 col-xs-6">
                                <div class="styled-select-filters">
                                    <?= Html::dropDownList('sort', $filter_sort, $filters, [
                                        'prompt' => 'Сортировать по дате',
                                        'id' => 'sort_date',
                                        'class' => 'url-filter'
                                    ]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <? foreach($models as $item): ?>
                    <div class="strip_booking">
                        <div class="row">
                            <div class="col-md-2 col-sm-2">
                                <div class="date">
                                    <span class="month">Номер заказа</span>
                                    <span class="day">
                                        <strong>#ID <?= $item->id ?></strong>
                                    </span>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-3 <? if(count($item->orderData) > 1): ?> first-order-data<? endif; ?>">
                            <? if(count($item->orderData)): ?>
                                <? foreach($item->orderData as $i =>  $data): ?>
                                <h3>
                                    <?= $data->name ?>
                                    <span>
                                        Взрослые: <b><?= $data-> adults ?></b> чел.
                                        <? if($data->children): ?> / Дети: <b><?= $data->children ?></b> чел.<? endif; ?>
                                    </span>
                                </h3>
                                <? endforeach ?>
                            <? endif; ?>
                            </div>
                            <div class="col-md-2 col-sm-3 text-center">
                                <div class="mt-20">Стоимость заказа:</div>
                                <strong><?= $item->totalPriceFormat ?></strong>
                            </div>
                            <div class="col-md-2 col-sm-3">
                                <ul class="info_booking">
                                    <li>
                                        <strong>Заказ создан</strong>
                                        <?= date($item::OUT_DATE_FORMAT, $item->create_timestamp) ?>
                                    </li>
                                    <li>
                                        <strong>Заказ оплачен</strong>
                                        <? if($item->status === $item::STATUS_SUCCESS): ?>
                                        <?= date($item::OUT_DATE_FORMAT, $item->paid_timestamp) ?>
                                        <? else: ?>
                                        <?= $item::getStatusName($item->status) ?>
                                        <? endif; ?>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-2 col-sm-2">
                                <div class="booking_buttons">
                                    <? if($item->status !== $item::STATUS_SUCCESS): ?>
                                    <a href="<?= $item->linkPay ?>" class="btn_2">Оплатить заказ</a>
                                    <a href="<?= $item->linkCancel ?>" class="btn_4">Отменить заказ</a>
                                    <? else: ?>
                                    <a href="<?= $item->linkDetail ?>" class="btn_3">Детально</a>
                                    <? endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <? endforeach; ?>
                <? else: ?>
                    <div class="text-center">
                        <h3>Нет записей для отображения!</h3>
                    </div>
                <? endif; ?>
                </section>
                <? if($pages->getPageCount() > 1): ?>
                <div class="text-center">
                    <?= LinkPager::widget([
                        'pagination' => $pages,
                        'options'    => [
                            'class' => 'pagination'
                        ]
                    ]); ?>
                    <!-- end pagination-->
                </div>
                <? endif; ?>
            </div>
        </div>
    </div>
</main>

frontend/views/users/passwd.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<header class="not-sticky">
    <div id="top_line">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-9 col-xs-9">
                    <i class="icon-phone"></i><strong>+995 595-73-33-11</strong>
                    <span id="opening"><i class="icon-phone"></i><strong>+995 595-71-33-11</strong></span>
                    <span id="opening"><i class="icon-mail-1"></i><?= Yii::$app->options->get('primary_email') ?></span>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-3">
                    <ul id="top_links">
                        <li id="social_top">
                            <a href="#0"><i class="icon-facebook"></i></a>
                            <a href="#0"><i class="icon-twitter"></i></a>
                            <a href="#0"><i class="icon-google"></i></a>
                            <a href="#0"><i class="icon-instagramm"></i></a>
                            <a href="#0"><i class="icon-vimeo"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- End row -->
        </div>
        <!-- End container-->
    </div>
    <!-- End top line-->
</header>
<main class="full-page">
    <section id="hero" class="login">
        <div class="container">
            <div class="row mb-30">
                <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                    <div id="login">
                        <div class="text-center">
                            <a href="/">
                                <img src="/img/logo_sticky_2x.png" alt="<?= Yii::$app->options->get('home_title') ?>" data-retina="true" class="img-responsive">
                            </a>
                        </div>
                        <hr>
                        <div class="text-center">
                            <strong>Забыли пароль?</strong>
                            <p><small>Мы вышлем вам инструкции по электронной почте</small></p>
                        </div>
                        <hr>
                        <form action="" method="post">
                            <div class="form-group">
                                <label for="">Ваш email:</label>
                                <input type="text" class="form-control" placeholder="email@example.com">
                            </div>
                            <button type="submit" class="btn_full">Сброс пароля</button>
                            <a href="<?= Yii::$app->user->url->signin ?>" class="btn_full_outline">Войти</a>
                        </form>
                    </div>
                    <div class="text-center">
                        <?= Yii::$app->options->get('copyright') ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main><!-- End main -->

frontend/views/users/signin.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<header class="not-sticky">
    <div id="top_line">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-9 col-xs-9">
                    <i class="icon-phone"></i><strong>+995 595-73-33-11</strong>
                    <span id="opening"><i class="icon-phone"></i><strong>+995 595-71-33-11</strong></span>
                    <span id="opening"><i class="icon-mail-1"></i><?= Yii::$app->options->get('primary_email') ?></span>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-3">
                    <ul id="top_links">
                        <li id="social_top">
                            <a href="#0"><i class="icon-facebook"></i></a>
                            <a href="#0"><i class="icon-twitter"></i></a>
                            <a href="#0"><i class="icon-google"></i></a>
                            <a href="#0"><i class="icon-instagramm"></i></a>
                            <a href="#0"><i class="icon-vimeo"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- End row -->
        </div>
        <!-- End container-->
    </div>
    <!-- End top line-->
</header>
<main class="full-page">
    <section id="hero" class="login">
        <div class="container">
            <div class="row mb-30">
                <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                    <div id="login">
                        <div class="text-center">
                            <a href="/">
                                <img src="/img/logo_sticky_2x.png" alt="<?= Yii::$app->options->get('home_title') ?>" data-retina="true" class="img-responsive">
                            </a>
                        </div>
                        <hr>
                        <? $form = ActiveForm::begin(['id' => 'login-form']); ?>
                            <?= $form->field($model, 'email',  [
                                'template' => '{input}{error}',
                                'inputOptions' => [
                                    'class'        => 'form-control',
                                    'autocomplete' => 'off',
                                    'placeholder'  => $model->getAttributeLabel('email'),
                                ],
                                'options' => [
                                    'class' => 'form-group'
                                ]
                            ])->label(false)->hint(false) ?>
                            <?= $form->field($model, 'password',  [
                                'template' => '{input}{error}',
                                'inputOptions' => [
                                    'class'        => 'form-control',
                                    'autocomplete' => 'off',
                                    'placeholder'  => $model->getAttributeLabel('password'),
                                ],
                                'options' => [
                                    'class' => 'form-group'
                                ]
                            ])->passwordInput()->label(false)->hint(false) ?>
                            <p class="small">
                                <a href="<?= Yii::$app->user->url->reset_password ?>">Забыли пароль?</a>
                            </p>
                            <button type="submit" class="btn_full">Войти</button>
                            <a href="<?= Yii::$app->user->url->signup ?>" class="btn_full_outline">
                                Регистрация
                            </a>
                        <? ActiveForm::end(); ?>
                    </div>
                    <div class="text-center">
                        <?= Yii::$app->options->get('copyright') ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main><!-- End main -->