common/models/Comment.php
<?php
/**
 * Comments
 * @author Demid [Alexander Pilipenko] <webdemid@gmail.com>
 * @since 1.0
 */

namespace common\models;

use common\ext\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

/**
 * Database structure
 *
 * @property int(11)      $id                 - Unique identificator
 * @property int(11)      $item_id            - text
 * @property int(11)      $user_id            - text
 * @property varchar(100) $module             - text
 * @property text         $content            - text
 * @property text         $data               - text
 * @property varchar(19)  $date               - text
 * @property tinyint(1)   $moderation         - text
 * @property tinyint(1)   $published          - text
 */
class Comment extends ActiveRecord
{
    /**
     * Active recording
     */
    const PUBLISHED_ON = 1;

    /**
     * Inactive recording
     */
    const PUBLISHED_OFF = 0;

    /**
     * Active moderation
     */
    const MODERATION_ON = 1;

    /**
     * Inactive moderation
     */
    const MODERATION_OFF = 0;

    /**
     * Date format in the database
     */
    const PROP_DATE_FORMAT = 'Y-m-d H:i:s';

    /**
     * Date output format
     */
    const OUT_DATE_FORMAT = 'm.d.Y H:i:s';

    /**
     * Sort channels field
     */
    const ORDER_BY_SORTING = 'date';

    /**
     * Date in UNIX TIMESTAMP format
     * @var integer
     */
    public $date_timestamp;

    /**
     * Information from the guest
     * @var Array
     */
    private $json_data;

    /**
     * Guest name
     * @var String
     */
    public $name;

    /**
     * Guest email
     * @var String
     */
    public $email;

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return '{{%comments}}';
    }

    /**
     * @inheritdoc
     * @return array
     */
    public function rules() {
        return [
            [['module', 'item_id'], 'required'],
            ['module', 'string', 'max' => '255'],
            [['content', 'data'], 'string', 'max' => '65535'],
            [['content', 'data'], 'trim'],
            ['date', 'default', 'value' => date(self::PROP_DATE_FORMAT)],
            ['data', 'safe'],
            ['email', 'email'],

            // Filers
            ['name', 'filter', 'filter' => function ($value) {
                return \yii\helpers\Html::encode($value);
            }],

            [['item_id', 'user_id', 'moderation', 'published'], 'integer'],
            [['user_id', 'moderation'], 'default', 'value' => 0],
            ['published', 'default', 'value' => self::PUBLISHED_ON]
        ];
    }

    /**
     * @inheritdoc
     * @return array
     */
    public function attributeLabels() {
        return [
            'content' => 'Комментарий',
            'email' => 'E-Mail гостя',
            'item_id' => 'Идентификатор записи',
            'moderation' => 'Модерация',
            'module' => 'Модуль',
            'name' => 'Имя гостя',
            'published' => 'Публикация',
            'user_id' => 'Идентификатор пользователя',
        ];
    }

    /**
     * @inheritdoc
     */
    public function afterFind() {
        $this->date_timestamp = strtotime($this->date);

        if ($this->data) {
            $this->json_data = Json::decode($this->data);
            $this->name = $this->json_data['name'];
            $this->email = $this->json_data['email'];
        }
    }

    /**
     * @inheritdoc
     * @return boolean
     */
    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        if ($this->name || $this->email) {
            $this->data = Json::encode([
                'name' => $this->name,
                'email' => $this->email
            ]);
        }

        return true;
    }

    /**
     * The first character of the name string
     * @return String
     */
    public function getSymbolName() {
        if($this->data) {
            return mb_substr($this->name, 0, 1);
        }
        return '-';
    }

    /**
     * Get user object
     * @return common\models\User;
     */
    public function getUser() {
        return $this->hasOne(User::classname(), ['id' => 'user_id']);
    }
}

backend/controllers/CommentController.php
<?php

/**
 * Comments
 * @author Demid [Alexander Pilipenko] <webdemid@gmail.com>
 * @since 1.1
 */

namespace backend\controllers;

use backend\components\BackendController;
use backend\models\Search;
use backend\widgets\Notify;
use common\models\Comment;
use Yii;
use yii\data\Pagination;
use yii\helpers\Url;

class CommentController extends BackendController
{

    public $pageSize = 20; // Number of entries per page

    /**
     * All comments
     * @return String
     */
    public function actionIndex()
    {
        // Remember links for btnAction
        Url::remember(Yii::$app->request->url, 'save-exit');

        $this->view->title = 'Все комментарии';
        $this->breadcrumbs[] = $this->view->title;
        $search = (new Search)->apply(Yii::$app->request->get('search'));
        $total = Comment::find()
        //->andFilterWhere(['AND', ['like', 'name', $search]])
            ->orderBy([Comment::ORDER_BY_SORTING => SORT_DESC])
            ->count();

        $pages = new Pagination([
            'totalCount' => $total,
            'pageSize' => $this->pageSize,
        ]);

        $comments = Comment::find()
        //->andFilterWhere(['AND', ['like', 'name', $search]])
            ->orderBy([Comment::ORDER_BY_SORTING => SORT_DESC])
            ->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('index', [
            'comments' => $comments,
            'pages' => $pages,
            'total' => $total,
            'search' => $search,
        ]);
    }

    /**
     * Preview comment
     * @return [type] [description]
     */
    public function actionPreview($id)
    {
        if (!Yii::$app->request->isAjax) {
            die('Access denied');
        }

        $model = Comment::findOne((int) $id);

        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        return $this->renderPartial('preview', [
            'model' => $model,
        ]);
    }

    /**
     * Moderation comment
     * @param Integer $id
     * @return String
     */
    public function actionModeration($id)
    {
        $model = Comment::findOne((int) $id);

        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        if ($model->load(Yii::$app->request->post()) && $model->save(true)) {
            $model->update(true);

            Yii::$app->session->setFlash('success', 'Комментарий успешно отредактирован!');
            return $this->redirectBtnAction(Yii::$app->request->url, 'save');
        }

        return $this->render('moderation', ['model' => $model]);
    }

    /**
     * Remove comment
     * @param Integer $id
     * @return Strinf
     */
    public function actionRemove($id)
    {
        $model = Comment::findOne((int) $id);

        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        $model->delete();

        Yii::$app->session->setFlash('success', 'Комментарий успешно удален!');
        return $this->redirect(Url::previous('save-exit'));
    }

    /**
     * Published Status Updates
     * @param  integer $id [description]
     * @return [array]
     */
    public function actionPublished($id)
    {
        if (Yii::$app->request->isAjax) {

            $model = Comment::find()
                ->select(['id', 'published'])
                ->where(['id' => (int) $id])
                ->one();

            if (is_null($model)) {
                return Notify::danger('Не удалось найти #ID:' . inval($id) . '!');
            }

            if ((boolean) Yii::$app->request->get('published')) {
                $model->published = filter_var(Yii::$app->request->get('published'), FILTER_VALIDATE_BOOLEAN);
            }

            $model->update(false);

            return Notify::success('Запись #ID:' . $model->id . ' успешно обновленна!');
        }
    }
}

frontend/controllers/CommentController.php
<?php

/**
 * Receiving and processing incoming comments
 * @author Demid [Alexander Pilipenko] <webdemid@gmail.com>
 * @since 1.1
 */

namespace frontend\controllers;

use common\models\Comment;
use frontend\components\FrontendController;
use frontend\models\FormComment;
use Yii;
use yii\data\Pagination;
use yii\web\Response;

/**
 * Site controller
 */
class CommentController extends FrontendController
{

    /**
     * Container for ajax replies
     * @var array
     */
    public $ajaxResponse = [
        'body' => false,
    ];

    /**
     * @inheritdoc
     * @return boolean
     */
    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if ($action->id != 'captcha' && !Yii::$app->request->isAjax) {
                die('Access denied');
            }
            return true;
        }
        return false;
    }

    /**
     * Data handler from the form
     * @return JSON String
     */
    public function actionForm()
    {
        $model = new FormComment;

        if (Yii::$app->user->isGuest) {
            $model->setScenario($model::SCENARIO_GUEST);
        }

        if (Yii::$app->request->isPost) {
            if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->save()) {
                $model->unsetAttributes();
                $model->is_success = true;
            }
        }

        $this->ajaxResponse['body'] = $this->renderPartial('form', [
            'model' => $model,
        ]);

        Yii::$app->response->format = Response::FORMAT_JSON;
        return $this->ajaxResponse;
    }

    /**
     * Paginate comments output
     * @return JSON String
     */
    public function actionList($id, $module)
    {

        $_where = [
            'item_id' => (int) $id,
            'module' => $module,
            'published' => Comment::PUBLISHED_ON
        ];

        // Only comments that have been moderated
        if(Yii::$app->options->get('only_moderation')) {
            $_where['moderation'] = Comment::MODERATION_ON;
        }

        $total = Comment::find()
            ->where($_where)
            ->orderBy([Comment::ORDER_BY_SORTING => SORT_DESC])
            ->count();

        $pages = new Pagination([
            'totalCount' => $total,
            'pageSize' => Yii::$app->options->get('page_limit_comments'),
        ]);

        $next_page = (int) Yii::$app->request->get('page', 1);
        $pages->page = $next_page;

        // Comments
        $comments = Comment::find()
            ->where($_where)
            ->orderBy([Comment::ORDER_BY_SORTING => SORT_DESC])
            ->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        $this->ajaxResponse['offset'] = $pages->page;

        // Next page
        $this->ajaxResponse['nextPage'] = ($next_page++ >= $pages->pageCount-1) ? 0 : $next_page;

        // List comments
        $this->ajaxResponse['body'] = $this->renderPartial('list', [
            'comments' => $comments,
        ]);

        Yii::$app->response->format = Response::FORMAT_JSON;
        return $this->ajaxResponse;
    }

    /**
     * @inheritdoc
     * @link http://www.yiiframework.com/doc-2.0/yii-captcha-captchaaction.html
     * @return array
     */
    public function actions()
    {
        return [
            'captcha' => [
                'backColor' => 0xFFFFFF,
                'class' => 'common\ext\captcha\CaptchaAction',
                'fontFile' => '@yii/captcha/SpicyRice.ttf',
                'foreColor' => 0x576371,
                'height' => 40,
                'offset' => 4,
                'transparent' => false,
                'width' => 160,
            ],
        ];
    }
}

backend/views/comment/index.php
<?php

use yii\helpers\StringHelper;
use yii\helpers\Html;
use yii\bootstrap\Alert;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\widgets\LinkPager;

$this->context->smallTitle = 'Модуль "Комментарии" предназначен для управления и настройки комментариев на сайте.';

?>
<? if(count($comments)): ?>
<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Все комментарии</h5>
        <small class="display-block text-muted">
            <?= $search ? 'Всего найдено' :  'Всего комментариев' ?>: <?= $pages->totalCount ?>
        </small>
        <div class="heading-elements">
            <?= Html::beginForm(Url::to([Yii::$app->controller->id . '/index']), 'get', ['class' => 'heading-form']) ?>
                <div class="form-group has-feedback">
                    <?//= Html::hiddenInput('module', $newsFeed->id)?>
                    <?= Html::textInput('search', $search, ['class' => 'form-control input-xs', 'placeholder' => 'Поиск...']) ?>
                    <div class="form-control-feedback">
                        <i class="icon-search4 text-size-base text-muted"></i>
                    </div>
                </div>
            <?= Html::endForm() ?>
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table text-nowrap">
                <thead>
                    <tr>
                        <th width="5%">#ID</th>
                        <th width="30%">Автор</th>
                        <th width="10%">Модерация</th>
                        <th width="35%">Комментарий</th>
                        <th class="text-center" width="10%" data-toggle="true">Публикация</th>
                        <th class="text-center" width="10%">
                            <i class="icon-menu-open2" data-popup="tooltip" title="Действие" data-placement="left"></i>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <? foreach($comments as $item): ?>
                    <tr>
                        <td><?= $item->id ?></td>
                        <td>
                            <div class="media-left media-middle">
                                <? if($item->user !== null): ?>
                                <img src="<?= $item->user->pathLogo ?>" alt="<?= Html::encode($item->user->nameTogether) ?>" style="width:32px;height:32px;" class="btn-rounded">
                                <? else: ?>
                                <span class="btn bg-primary-400 btn-rounded btn-icon btn-xs">
                                    <span class="letter-icon">
                                        <?= $item->symbolName ?>
                                    </span>
                                </span>
                                <? endif ?>
                            </div>
                            <div class="media-body">
                                <? if($item->user !== null): ?>
                                    <a href="<?= $item->user->profileLink ?>" class="display-inline-block text-semibold letter-icon-title">
                                        <?= $item->user->nameTogether ?>
                                    </a>
                                    <div class="text-muted text-size-small">
                                        <span>Зарегистрированный</span>
                                    </div>
                                <? else: ?>
                                    <span class="display-inline-block text-default text-semibold letter-icon-title">
                                        <?= $item->name ?>
                                    </span>
                                    <div class="text-muted text-size-small">
                                        <a href="mailto:<?= $item->email ?>">
                                            <?= $item->email ?>
                                        </a>
                                    </div>
                                <? endif ?>
                                <span class="text-muted">
                                    Без модерации
                                </span>
                            </div>
                        </td>
                        <td class="text-center">
                            <? if($item->moderation): ?>
                                <i class="icon-checkmark3 text-success" title="Модерация выполнена"></i>
                            <? else: ?>
                                <i class="icon-warning text-muted" title="Без модерации"></i>
                            <? endif; ?>
                        </td>
                        <td class="text-left">
                            <div class="text-muted">
                                <div>
                                    <?= StringHelper::truncate($item->content, 50, '...') ?>
                                </div>
                                <a href="/<?= Yii::$app->controller->id ?>/preview?id=<?= $item->id ?>" data-toggle="modal-ajax" data-target="#preview-comment">
                                    Быстрый просмотр...
                                </a>
                            </div>
                        </td>
                        <td class="text-center">
                            <div class="checkbox checkbox-switchery switchery-xs" title="Вкл/Выкл">
                                <label>
                                    <?= Html::checkbox('Published['. $item->id .']', $item->published, [
                                        'class' => 'switchery',
                                        'onclick' => "ChangeRequest('" . Url::to([
                                            Yii::$app->controller->id . '/published',
                                            'id' => $item->id
                                        ]) . "', {published: this.checked});"
                                    ]); ?>
                                </label>
                            </div>
                        </td>
                        <td class="text-center">
                            <ul class="icons-list">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Действия">
                                        <i class="icon-menu7"></i>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <li>
                                            <?= Html::a('<i class="icon-pencil5"></i>Редактировать', [
                                                Yii::$app->controller->id . '/moderation?id=' . $item->id
                                            ]) ?>
                                        </li>
                                        <li>
                                            <?= Html::a('<i class="icon-bin"></i>Удалить', [
                                                Yii::$app->controller->id . '/remove?id=' . $item->id
                                            ], [
                                                'onclick' => "return confirm('Вы уверены что хотите удалить данные?');"
                                            ]) ?>
                                        </li>
                                    </ul>
                                </li>
                            </ul><!-- /.icons-list -->
                        </td>
                    </tr>
                    <? endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="mb-20">
    <?= LinkPager::widget([
        'pagination' => $pages,
        'options'    => [
            'class' => 'pagination pagination-xs'
        ]
    ]); ?>
</div>

<!-- Basic modal -->
<div id="preview-comment" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
<!-- /basic modal -->

<? else: Alert::begin(['options' => ['class' => 'bg-info alert-styled-left']]); ?>
    Не удается найти комментарии для отображения
<? Alert::end(); endif;?>
<!-- /table with togglable columns -->

backend/views/comment/moderation.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use common\models\Groupmodels;
use backend\widgets\FilesWidget;

$this->context->breadcrumbs[] = [
    'label' => 'Все комментарии',
    'url'   => '/'. $this->context->id .'/index'
];

$pageName = 'Редактировать комментарий';
$this->context->view->title = $pageName;
$this->context->breadcrumbs[] = $pageName;

?>
<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title"><?= $pageName ?></h5>
    </div>
    <div class="panel-body">
    <? $form = ActiveForm::begin([
        'id' => $this->context->id . '-form',
        'options' => [
            'role'    => 'form',
            'class' => 'form-horizontal'
        ]
    ]); ?>
        <div class="row">
            <div class="col-sm-12">
            <? if($model->user !== null): ?>
                <div class="form-group">
                    <label class="control-label col-lg-2">Пользователь</label>
                    <div class="col-lg-10">
                        <div class="form-control-static">
                            <a href="<?= $model->user->profileLink ?>" target="_blank">
                                <?= $model->user->nameTogether ?>
                            </a>
                        </div>
                    </div>
                </div>
            <? else: ?>
                <?= $form->field($model, 'name', [
                    // Begin input theme
                    'template' => '{label}<div class="col-lg-10">{input}{hint}{error}</div>',
                    // End input theme
                    'inputOptions' => [
                        'class' => 'form-control'
                    ],
                    'options' => [
                        'class' => 'form-group'
                    ]
                ])->hint(false)->label(
                    $model->getAttributeLabel('name') .
                    ($model->isAttributeRequired('name')? ' : <span class="text-danger">*</span>' : ' :'),
                    ['class' => 'control-label col-lg-2']
                ) ?>

                <?= $form->field($model, 'email', [
                    // Begin input theme
                    'template' => '{label}<div class="col-lg-10">{input}{hint}{error}</div>',
                    // End input theme
                    'inputOptions' => [
                        'class' => 'form-control'
                    ],
                    'options' => [
                        'class' => 'form-group'
                    ]
                ])->hint(false)->label(
                    $model->getAttributeLabel('email') .
                    ($model->isAttributeRequired('email')? ' : <span class="text-danger">*</span>' : ' :'),
                    ['class' => 'control-label col-lg-2']
                ) ?>
            <? endif ?>

                <?= $form->field($model, 'content', [
                    // Begin input theme
                    'template' => '{label}<div class="col-lg-10">{input}{hint}{error}</div>',
                    // End input theme
                    'inputOptions' => [
                        'class' => 'form-control',
                        'rows'  => 15
                    ],
                    'options' => [
                        'class' => 'form-group'
                    ]
                ])->textarea()->hint('Полное описание или HTML шаблон')->label(
                    $model->getAttributeLabel('content') .
                    ($model->isAttributeRequired('content')? ' : <span class="text-danger">*</span>' : ' :'),
                    ['class' => 'control-label col-lg-2']
                ) ?>

                <div class="col-lg-10 col-lg-offset-2">
                    <div class="form-group">
                        <?= $form->field($model, 'moderation', [
                            'template' => '<label class="checkbox-inline">{input}'. $model->getAttributeLabel('moderation') .'{hint}</label>',
                        ])->label(false)->checkbox(['class' => 'styled'], false)->hint('Проверка содержимого комментария была выполнена администратором сайта.') ?>
                    </div>
                </div>

                <div class="col-lg-10 col-lg-offset-2">
                    <div class="form-group">
                        <?= $form->field($model, 'published', [
                            'template' => '<label class="checkbox-inline">{input}'. $model->getAttributeLabel('published') .'{hint}</label>',
                        ])->label(false)->checkbox(['class' => 'styled'], false)->hint('Комментарий будет выведен на странице ресурса') ?>
                    </div>
                </div>
            </div>
        </div><!-- /.row -->
        <hr>
        <div class="text-right">
            <button type="submit" name="btnAction" value="save" class="btn bg-teal-400 btn-sm">
                <i class="icon-checkmark3 position-left"></i> Сохранить
            </button>
            <button type="submit" name="btnAction" value="save-exit" class="btn btn-primary btn-sm">
                <i class="icon-undo2 mr-5"></i> Сохр. и закрыть
            </button>
            <? if(!$model->isNewRecord): ?>
            <?= Html::a('<i class="icon-bin"></i>Удалить', [
                Yii::$app->controller->id . '/'. $model->id .'/remove'
            ], [
                'onclick' => "return confirm('Вы уверены что хотите удалить данные?');",
                'class' => 'btn btn-danger btn-sm'
            ]) ?>
            <? endif; ?>
        </div>
    <? ActiveForm::end(); ?>
    </div><!-- /.panel-body -->
</div>

backend/views/comment/preview.php
<div class="modal-header bg-primary">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h5 class="modal-title">
        Комментарий
        <span class="mr-10">
            #<?= $model->id ?>
        </span>
    </h5>
</div>
<div class="modal-body">
    <?= $model->content ?>
</div>
<hr class="mt-5">
<div class="modal-footer row">
    <div class="col-sm-6 text-left">
        <span class="text-muted mr-5">Автор:</span>
        <span class="text-semibold">
        <? if($item->user !== null): ?>
            <?= $model->user->nameTogether ?>
        <? else: ?>
            <?= $model->name ?>
        <? endif; ?>

        </span>
    </div>
    <div class="col-sm-6">
        <?= date('d M Y H:s', $model->date_timestamp) ?>
    </div>
</div>