backend/controllers/UsersController.php
<?php

/**
 * User Accounts
 * @author Demid [Alexander Pilipenko] <webdemid@gmail.com>
 * @since 1.1
 */

namespace backend\controllers;

use backend\components\BackendController;
use backend\components\MenuComponent;
use common\models\PasswordResetRequestForm;
use common\models\ResetPasswordForm;
use common\models\SigninForm;
use common\models\SignupForm;
use common\models\User;
use Yii;
use yii\base\InvalidParamException;
use yii\data\Pagination;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\ForbiddenHttpException;

class UsersController extends BackendController {

    public $pageSize = 15; // Number of entries per page

    /**
     * @inheritdoc
     * @return boolean
     */
    public function beforeAction($action) {
        if (parent::beforeAction($action)) {

            // Add button in the top menu
            $this->headMenu[] = new MenuComponent([
                'label' => 'Добавить аккаунт',
                'icon' => 'icon-plus22 position-left',
                'url' => Url::to('/users/add'),
            ]);

            // Private variable
            $_actions = ['blocked', 'passwd'];

            // Checking for permission
            if(($action->id == 'blocked' && !\Yii::$app->user->can('lockingProfiles'))
                || ($action->id == 'passwd' && !\Yii::$app->user->can('changePassword'))
            ) {
                throw new ForbiddenHttpException('Access denied');
            }

            return true;
        }

        return false;
    }

    /**
     * [actionIndex description]
     * @return [type] [description]
     */
    public function actionIndex() {

        // Remember links for btnAction
        Url::remember(Yii::$app->request->url, 'save-exit');
        Url::remember('/' . Yii::$app->controller->id . '/add', 'save-new');

        // Header
        $this->view->title = 'Все аккаунты';
        $this->breadcrumbs[] = $this->view->title;
        //$this->pageTitle = $this->view->title;
        // $this->breadcrumbs[] = [
        //  'label' => 'Администраторы',
        //  'url' => ['/users']
        // ];

        $total = User::find()->count();
        $pages = new Pagination([
            'totalCount' => $total,
            'pageSize' => $this->pageSize,
        ]);

        $usersModel = User::find()
            ->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('index', [
            'users' => $usersModel,
            'pages' => $pages,
            'total' => $total,
        ]);
    }

    /**
     * [actionProfile description]
     * @param  [type] $id [description]
     * @return [type]     [description]
     */
    public function actionProfile($id) {
        if (!Yii::$app->user->can('accessProfile') && Yii::$app->user->identity->id != $id) {
            throw new ForbiddenHttpException('Access denied');
        }

        return $this->render('profile', ['id' => $id]);
    }

    /**
     * Block access to resources
     * @param  int $id
     * @return string
     */
    public function actionBlocked($id) {
        $model = User::find()
            ->select(['id', 'status'])
            ->where(['id' => (int) $id])
            ->one();

        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        if ($model->status !== User::STATUS_BLOCKED) {
            $model->updateAttributes(['status' => User::STATUS_BLOCKED]);
            Yii::$app->session->setFlash('success', 'Аккаунт успешно заблокирован!');
        } else {
            Yii::$app->session->setFlash('danger', 'Аккаунт уже заблокирован!');
        }

        return $this->redirect(Url::previous());
    }

    /**
     * Create an account
     * @return string
     */
    public function actionAdd() {
        $model = new User;

        if ($model->load(Yii::$app->request->post()) && $model->save(true)) {
            Yii::$app->session->setFlash('success', 'Аккаунт успешно добавлен!');
            return $this->redirectBtnAction('/' . Yii::$app->controller->id . '/edit?id=' . $model->id, 'save');
        }

        return $this->render('item', ['user' => $model]);
    }

    /**
     * Edit account
     * @param  int $id
     * @return string
     */
    public function actionEdit($id) {
        $model = User::findOne((int) $id);

        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        if ($model->load(Yii::$app->request->post()) && $model->save(true)) {
            Yii::$app->session->setFlash('success', 'Аккаунт успешно отредактирован!');
            return $this->redirectBtnAction(Yii::$app->request->url, 'save');
        }

        return $this->render('item', ['user' => $model]);
    }

    /**
     * Password changes in your account
     * @param  int $id
     * @return string
     */
    public function actionPasswd($id) {
        $send_email = (int) Yii::$app->request->post('send_email');

        $model = User::find()
            ->select(['id', 'password_reset_token', 'first_name', 'second_name', 'email'])
            ->where(['id' => (int) $id])
            ->one();

        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        if (!User::isPasswordResetTokenValid($model->password_reset_token)) {
            $model->generatePasswordResetToken();
            $model->save(false);
        }

        try {
            $ResetPassword = new ResetPasswordForm($model->password_reset_token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($ResetPassword->load(Yii::$app->request->post()) && $ResetPassword->validate() && $ResetPassword->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль был сохранен.');

            // Send password to account email
            if($send_email) {
                $send_email = false;

                \Yii::$app->mailer->compose([
                    'html' => 'passwd-html',
                    'text' => 'passwd-text',
                ], [
                    'password' => $ResetPassword->password,
                    'nameTogether' => $model->nameTogether
                ])
                    ->setFrom([\Yii::$app->params['supportEmail'] => \Yii::$app->name . ' robot'])
                    ->setTo($model->email)
                    ->setSubject('Изменение пароля для ' . \Yii::$app->name)
                    ->send();
            }
        }

        return $this->render('passwd', [
            'user' => $model,
            'send_email' => $send_email,
            'ResetPassword' => $ResetPassword
        ]);
    }

    /**
     * Deleting an account
     * @param  int $id
     * @return string
     */
    public function actionRemove($id) {
        $model = User::findOne((int) $id);

        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        $model->delete();

        Yii::$app->session->setFlash('success', 'Аккаунт успешно удален!');
        return $this->redirect(Url::previous('save-exit'));
    }

    /**
     * [actionLogin description]
     * @return [type] [description]
     */
    public function actionSignin() {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $SigninForm = new SigninForm();

        if ($SigninForm->load(Yii::$app->request->post()) && $SigninForm->login()) {
            return $this->goBack();
        } else {
            return $this->render('signin', ['Signin' => $SigninForm]);
        }
    }

    /**
     * [actionRequestPasswordReset description]
     * @return [type] [description]
     */
    public function actionRequestPasswordReset() {
        $PasswordReset = new PasswordResetRequestForm();

        if ($PasswordReset->load(Yii::$app->request->post()) && $PasswordReset->validate()) {
            if ($PasswordReset->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }

        }

        return $this->render('requestPasswordResetToken', [
            'PasswordReset' => $PasswordReset,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token) {

        try {
            $ResetPassword = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($ResetPassword->load(Yii::$app->request->post()) && $ResetPassword->validate() && $ResetPassword->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль был сохранен.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'ResetPassword' => $ResetPassword,
        ]);
    }

    /**
     * [actionSignup description]
     * @return [type] [description]
     */
    public function actionSignup() {
        //invite
        $signup = new SignupForm();
        if ($signup->load(Yii::$app->request->post())) {
            if ($user = $signup->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [

frontend/controllers/UsersController.php
<?php

/**
 * User Accounts
 * @author Demid [Alexander Pilipenko] <webdemid@gmail.com>
 * @since 1.1
 */

namespace frontend\controllers;

use common\models\Files;
use common\models\SigninForm;
use common\models\SignupForm;
use common\models\User;
use frontend\models\ChangeEmail;
use frontend\models\ChangeNotification;
use frontend\models\ChangePassword;
use common\models\Order;
use Yii;
use yii\web\Response;
use yii\data\Pagination;

class UsersController extends \frontend\components\FrontendController
{

    public $defaultPageSize = 10; // Number of entries per page

    /**
     * Profile info
     * @return String
     */
    public function actionProfile()
    {
        if(Yii::$app->user->isGuest) {
            return $this->redirect(Yii::$app->user->url->signin);
        }

        $model = User::findOne(Yii::$app->user->identity->id);

        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        if ($model->load(Yii::$app->request->post()) && $model->save(true)) {
            Yii::$app->session->setFlash('success', 'Данные профиля успешно изменены!');
            return $this->redirect(Yii::$app->request->url);
        }

        return $this->render('profile', ['model' => $model]);
    }

    /**
     * Settings account
     * @return String
     */
    public function actionSettings()
    {
        if(Yii::$app->user->isGuest) {
            return $this->redirect(Yii::$app->user->url->signin);
        }

        $model = User::findOne(Yii::$app->user->identity->id);
        if (is_null($model)) {
            throw new \yii\web\NotFoundHttpException();
        }

        // Password Updates
        $change_password = new ChangePassword;
        if ($change_password->load(Yii::$app->request->post()) && $change_password->update()) {
            Yii::$app->session->setFlash('success', 'Пароль успешно изменен!');
            return $this->redirect(Yii::$app->request->url);
        }

        // Email Updates
        $change_email = new ChangeEmail;
        if ($change_email->load(Yii::$app->request->post()) && $change_email->update()) {
            Yii::$app->session->setFlash('success', 'Email успешно изменен!');
            return $this->redirect(Yii::$app->request->url);
        }

        // Notification settings
        $change_notification = new ChangeNotification;
        $change_notification->setAttributes([
            'notification_new_tours' => $model->notification_new_tours,
            'notification_comp_news' => $model->notification_comp_news,
        ]);
        unset($model);

        if ($change_notification->load(Yii::$app->request->post()) && $change_notification->update()) {
            Yii::$app->session->setFlash('success', 'Настроки уведомлений успешно обновлены!');
            return $this->redirect(Yii::$app->request->url);
        }

        return $this->render('settings', [
            'change_password' => $change_password,
            'change_email' => $change_email,
            'change_notification' => $change_notification,
        ]);
    }

    /**
     * My orders
     * @return String
     */
    public function actionOrders($sort = null)
    {

        if(Yii::$app->user->isGuest) {
            return $this->redirect(Yii::$app->user->url->signin);
        }

        // Filters
        $filters = [
            'asc' => 'Сначала старые',
            'desc' => 'Сначала новые',
        ];

        // Order by filter
        $order_by = ['id' => SORT_DESC];
        if(isset($_GET['sort']) && $sort !== null) {
            if($sort == 'desc') {
                $order_by = [Order::ORDER_BY_SORTING => SORT_DESC];
            }
            if($sort == 'asc') {
                $order_by = [Order::ORDER_BY_SORTING => SORT_ASC];
            }
        }

        $total = Order::find()
            ->where(['user_id' => Yii::$app->user->identity->id])
            ->andWhere('status != :status', [':status' => Order::STATUS_CANCEL])
            ->orderBy($order_by)
            ->count();

        $pages = new Pagination([
            'totalCount' => $total,
            'pageSize' => $this->defaultPageSize,
        ]);

        $models = Order::find()
            ->where(['user_id' => Yii::$app->user->identity->id])
            ->andWhere('status != :status', [':status' => Order::STATUS_CANCEL])
            ->offset($pages->offset)
            ->limit($pages->limit)
            ->orderBy($order_by)
            ->all();

        return $this->render('orders', [
            'models' => $models,
            'pages' => $pages,
            'filters' => $filters,
            'filter_sort' => $sort
        ]);
    }

    /**
     * Authorization
     * @return String
     */
    public function actionSignin()
    {
        $this->layout = self::LAYOUT_WRAPPER_NAME;
        $model = new SigninForm;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->login();
            return $this->redirect(Yii::$app->user->url->profile);
        }

        return $this->render('signin', ['model' => $model]);
    }

    /**
     * Registration
     * @return String
     */
    public function actionSignup()
    {
        $this->layout = self::LAYOUT_WRAPPER_NAME;
        $model = new SignupForm;

        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            $model->login();
            return $this->redirect(Yii::$app->user->url->profile);
        }

        return $this->render('signup', ['model' => $model]);
    }

    /**
     * Restore password
     * @return String
     */
    public function actionPasswd()
    {
        return $this->render('passwd');
    }

    /**
     * Loading User avatar
     * @return String
     */
    public function actionAvatar()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->isAjax && Yii::$app->request->isPost && !Yii::$app->user->isGuest) {

            $image = new Files(['scenario' => Files::SCENARIO_IMAGE]);
            $user = Yii::$app->user->identity;

            if ($image->load(Yii::$app->request->post())) {
                $image->setRules(Yii::$app->params['upload'][Files::SCENARIO_IMAGE]);

                foreach ($user->files as $item) {
                    $item->delete();
                }

                if ($image->upload()) {
                    return [
                        'link' => $image->getImageLink($user->image_sizes[0]),
                        'item_id' => $image->item_id,
                        'size' => $image->filesize,
                        'id' => $image->id
                    ];
                }
            } else {
                return ['errors' => $image->errors];
            }
        } else {
            return ['access' => 'Access denied'];
        }

        return [];
    }

    /**
     * Exit
     * @return Object
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
}

backend/views/users/index.php
<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\bootstrap\ActiveForm;
use backend\models\Users;
use yii\bootstrap\Alert;

//$this->params['breadcrumbs'][] = $this->context->pageTitle;
$this->context->smallTitle = 'Управление зарегистрированными на сайте пользователями (создание, редактирование, блокировка аккаунта)';
?>

<!-- Table with togglable columns -->
<? if(count($users)): ?>
<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">Список всех аккаунтов</h5>
        <small class="display-block text-muted">
            Зарегистрировано: <?= $total ?> чел.
        </small>
        <div class="heading-elements">
            <ul class="icons-list">
                <li><a data-action="collapse"></a></li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-togglable table-hover">
            <thead>
                <tr>
                    <th data-toggle="true">#UID</th>
                    <th data-toggle="true">Имя/Фамилия</th>
                    <th data-hide="phone">Группа</th>
                    <th data-hide="phone,tablet">E-Mail</th>
                    <th data-hide="phone,tablet">Дата регистрации</th>
                    <th data-hide="phone,tablet">Дата редактирования</th>
                    <th data-hide="phone,tablet">Последный IP авторизации</th>
                    <th data-hide="phone">Последний визит</th>
                    <th data-hide="phone" class="text-center">Статус аккаунта</th>
                    <th class="text-center" style="width: 30px;">
                        <i class="icon-menu-open2" data-popup="tooltip" title="Действие" data-placement="left"></i>
                    </th>
                </tr>
            </thead>
            <tbody>
            <? foreach($users as $item): ?>
                <tr>
                    <td><?= $item->id ?></td>
                    <td><?= $item->nameTogether ?></td>
                    <td><?= $item->groupName ?></td>
                    <td><?= $item->email ?></td>
                    <td><?= (new DateTime())->setTimestamp($item->created_timestamp)->format('d.m.Y H:i:s') ?></td>
                    <td><?= (new DateTime())->setTimestamp($item->updated_timestamp)->format('d.m.Y H:i:s') ?></td>
                    <td><?= $item->last_auth_ip ?></td>
                    <td><?= (new DateTime())->setTimestamp($item->auth_timestamp)->format('d.m.Y H:i:s') ?></td>
                    <td class="text-center">
                        <span class="label <?= $item->getStatusLabel() ?>">
                            <?= $item->getStatusName() ?>
                        </span>
                    </td>
                    <td class="text-center">
                        <ul class="icons-list">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Действия">
                                    <i class="icon-menu7"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <? if(Yii::$app->user->can('accessProfile') || Yii::$app->user->identity->id == $item->id): ?>
                                    <li>
                                        <?= Html::a('<i class="icon-user"></i> Профиль', [
                                            Yii::$app->controller->id . '/'. $item->id . '/profile'
                                        ]) ?>
                                    </li>
                                    <? endif; ?>
                                    <li>
                                        <?= Html::a('<i class="icon-user-plus"></i> Редактировать', [
                                            Yii::$app->controller->id . '/' . $item->id . '/edit'
                                        ]) ?>
                                    </li>
                                    <? if($item->id != Yii::$app->user->identity->id && $item->status != $item::STATUS_BLOCKED): ?>
                                    <li>
                                        <?= Html::a('<i class="icon-user-block"></i> Заблокировать', [
                                            Yii::$app->controller->id . '/'. $item->id .'/blocked'
                                        ], [
                                            'onclick' => "return confirm('Вы уверены что хотите заблокировать аккаунт?');"
                                        ]) ?>
                                    </li>
                                    <? endif; ?>
                                    <? if(Yii::$app->user->can('changePassword')): ?>
                                    <li>
                                        <?= Html::a('<i class="icon-user-lock"></i> Изменить пароль', [
                                            Yii::$app->controller->id . '/' . $item->id . '/passwd'
                                        ], [
                                            'onclick' => "return confirm('Вы уверены что хотите изменить пароль?');"
                                        ]) ?>
                                    </li>
                                    <? endif; ?>
                                    <li>
                                        <?= Html::a('<i class="icon-user-cancel"></i> Удалить', [
                                            Yii::$app->controller->id . '/'. $item->id .'/remove'
                                        ], [
                                            'onclick' => "return confirm('Вы уверены что хотите удалить данные?');"
                                        ]) ?>
                                    </li>
                                </ul>
                            </li>
                        </ul><!-- /.icons-list -->
                    </td>
                </tr>
            <? endforeach; ?>
            </tbody>
        </table>
    </div><!-- /.panel-body -->
</div>
<? else: Alert::begin(['options' => ['class' => 'bg-info alert-styled-left']]); ?>
    Не удается найти пользователей для отображения
<? Alert::end(); endif;?>
<!-- /table with togglable columns -->

backend/views/users/profile.php
В разработке!

backend/views/users/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Забыли пароль?';
$this->params['bodyClasses'] = 'login-container';

?>
<!-- Main content -->
<div class="content-wrapper">
	<!-- Content area -->
	<div class="content">
		<!-- Password recovery -->
		<? $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
			<div class="login-form">
				<div class="text-center">
					<div class="icon-object border-warning text-warning">
						<i class="icon-spinner11"></i>
					</div>
					<h5 class="content-group">
						<?= $this->title ?>
						<small class="display-block">Мы вышлем вам инструкции по электронной почте</small>
					</h5>
				</div>
				<?= $form->field($PasswordReset, 'email',  [
					'template' => '{input}<div class="form-control-feedback"><i class="icon-mail5 text-muted"></i></div>{error}',
					'inputOptions' => [
						'class'        => 'form-control',
						'autocomplete' => 'off',
						'placeholder'  => $PasswordReset->getAttributeLabel('email'),
					],
					'options' => [
						'class' => 'form-group has-feedback'
					]
				])->label(false)->hint(false) ?>
				<?= Html::submitButton('Сброс пароля <i class="icon-arrow-right14 position-right"></i>', [
					'class' => 'btn btn-primary btn-block',
					'name'  => 'login-button'
				]) ?>
			</div>
			<div class="text-center">
				<?= Html::a('<i class="icon-arrow-left13 position-left"></i> Вернуться к форме входа', ['users/signin'], [
					'class' => 'btn btn-link'
				]) ?>
			</div>
		<?php ActiveForm::end(); ?>
		<!-- /password recovery -->
		<!-- Footer -->
		<div class="footer text-muted text-center">
			&copy; <?= date('Y') ?>. <?= \Yii::$app->id ?>
		</div>
		<!-- /footer -->
	</div>
	<!-- /content area -->
</div>
<!-- /main content -->

backend/views/users/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Востановления пароля';
$this->params['bodyClasses'] = 'login-container';

?>
<!-- Main content -->
<div class="content-wrapper">
	<!-- Content area -->
	<div class="content">
		<!-- Password recovery -->
		<? $form = ActiveForm::begin(['id' => 'password-reset-form']); ?>
			<div class="login-form">
				<div class="text-center">
					<div class="icon-object border-success text-success">
						<i class="icon-user-check"></i>
					</div>
					<h5 class="content-group">
						<?= $this->title ?>
						<small class="display-block">Пожалуйста, введите ваш новый пароль.</small>
					</h5>
				</div>
				<?= $form->field($ResetPassword, 'password',  [
					'template' => '{input}<div class="form-control-feedback"><i class="icon-user-lock text-muted"></i></div>{error}',
					'inputOptions' => [
						'class'        => 'form-control',
						'autocomplete' => 'off',
						'placeholder'  => $ResetPassword->getAttributeLabel('password')
					],
					'options' => [
						'class' => 'form-group has-feedback has-feedback-left'
					]
				])->passwordInput()->label(false)->hint(false) ?>
				<?= $form->field($ResetPassword, 'password_repeat',  [
					'template' => '{input}<div class="form-control-feedback"><i class="icon-user-lock text-muted"></i></div>{error}',
					'inputOptions' => [
						'class'        => 'form-control',
						'autocomplete' => 'off',
						'placeholder'  => $ResetPassword->getAttributeLabel('password_repeat')
					],
					'options' => [
						'class' => 'form-group has-feedback has-feedback-left'
					]
				])->passwordInput()->label(false)->hint(false) ?>
				<?= Html::submitButton('Сохранить пароль <i class="icon-arrow-right14 position-right"></i>', [
					'class' => 'btn btn-primary btn-block',
					'name'  => 'login-button'
				]) ?>
			</div>
		<?php ActiveForm::end(); ?>
		<!-- /password recovery -->
		<!-- Footer -->
		<div class="footer text-muted text-center">
			&copy; <?= date('Y') ?>. <?= \Yii::$app->id ?>
		</div>
		<!-- /footer -->
	</div>
	<!-- /content area -->
</div>
<!-- /main content -->

backend/views/users/signin.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Войдите в свой аккаунт';
$this->params['bodyClasses'] = 'login-container';

?>
<!-- Main content -->
<div class="content-wrapper">
    <!-- Content area -->
    <div class="content">
        <!-- Simple login form -->
        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
            <div class="login-form">
                <div class="text-center">
                    <div class="icon-object border-slate-300 text-slate-300">
                        <i class="icon-reading"></i>
                    </div>
                    <h5 class="content-group">
                        <?= $this->title ?>
                        <small class="display-block">Введите учетные данные ниже</small>
                    </h5>
                </div>
                <?= $form->field($Signin, 'email',  [
                    'template' => '{input}<div class="form-control-feedback"><i class="icon-mention text-muted"></i></div>{error}',
                    'inputOptions' => [
                        'class'        => 'form-control',
                        'autocomplete' => 'off',
                        'placeholder'  => $Signin->getAttributeLabel('email'),
                    ],
                    'options' => [
                        'class' => 'form-group has-feedback has-feedback-left'
                    ]
                ])->label(false)->hint(false) ?>
                <?= $form->field($Signin, 'password',  [
                    'template' => '{input}<div class="form-control-feedback"><i class="icon-lock2 text-muted"></i></div>{error}',
                    'inputOptions' => [
                        'class'        => 'form-control',
                        'autocomplete' => 'off',
                        'placeholder'  => $Signin->getAttributeLabel('password')
                    ],
                    'options' => [
                        'class' => 'form-group has-feedback has-feedback-left'
                    ]
                ])->passwordInput()->label(false)->hint(false) ?>
                <div class="form-group">
                    <?= $form->field($Signin, 'rememberMe', [
                        'template' => '<label class="checkbox-inline">{input}'. $Signin->getAttributeLabel('rememberMe') .'? </label>',
                    ])->label(false)->checkbox(['class' => 'styled'], false) ?>
                </div>
                <div class="form-group">
                    <?= Html::submitButton('Войти <i class="icon-circle-right2 position-right"></i>', [
                        'class' => 'btn btn-primary btn-block',
                        'name'  => 'login-button'
                    ]) ?>
                </div>
                <div class="text-center">
                    <?= Html::a('Забыли пароль?', ['users/request-password-reset']) ?>
                </div>
            </div>
        <?php ActiveForm::end(); ?>
        <!-- /simple login form -->
        <!-- Footer -->
        <div class="footer text-muted text-center">
            &copy; <?= date('Y') ?>. <?= \Yii::$app->id ?>
        </div>
        <!-- /footer -->
    </div>
    <!-- /content area -->
</div>
<!-- /main content -->