common/models/Tours.php
<?php

/**
 * Tours
 * @author Demid [Alexander Pilipenko] <webdemid@gmail.com>
 * @since 1.0
 */

namespace common\models;

use common\ext\db\ActiveRecord;
use common\ext\validators\TranslitFilter;
use Yii;
use yii\helpers\Json;
use \yii\helpers\StringHelper;

/**
 * Database structure
 *
 * @property int(11)      $id                     - Unique identificator
 * @property varchar(255) $cat_id                 - text
 * @property int(11)      $type_id                - text
 * @property varchar(255) $restrictions           - text
 * @property varchar(255) $name                   - text
 * @property varchar(255) $alias                  - text
 * @property text         $description            - text
 * @property varchar(200) $meta_description       - text
 * @property varchar(250) $meta_keywords          - text
 * @property text         $included_in_price      - text
 * @property text         $not_included_in_price  - text
 * @property int(11)      $rating                 - text
 * @property int(11)      $rating_votes           - text
 * @property int(11)      $views                  - text
 * @property int(11)      $stars                  - text
 * @property tinyint(1)   $selling                - text
 * @property tinyint(1)   $noindex                - text
 * @property tinyint(1)   $fixed                  - text
 * @property tinyint(1)   $published              - text
 *
 */
class Tours extends ActiveRecord
{

    /**
     * Active tour for sale
     */
    const SELLING_ON = 1;

    /**
     * Sale tour is not active
     */
    const SELLING_OFF = 0;

    /**
     * Active recording
     */
    const PUBLISHED_ON = 1;

    /**
     * Inactive recording
     */
    const PUBLISHED_OFF = 0;

    /**
     * Enable indexing
     */
    const NOINDEX_ON = 1;

    /**
     * Disable indexing
     */
    const NOINDEX_OFF = 0;

    /**
     * Enable fixed tour
     */
    const FIXED_ON = 1;

    /**
     * Disable fixed tour
     */
    const FIXED_OFF = 0;

    /**
     * Date output format
     */
    const OUT_DATE_FORMAT = 'd.m.Y H:i';

    /**
     * Sort tours field
     */
    const ORDER_BY_FIXED = 'fixed';

    /**
     * Default image size
     */
    const DEFAULT_SIZE = '100x100';

    /**
     * Pattern for dividing lines
     */
    const PATTERN_PREG_SPLIT = '/\r\n|\r|\n/';

    /**
     * Default minimum price
     * @var String
     */
    public $default_price;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tours}}';
    }

    /**
     * @inheritdoc
     * @return array
     */
    public function rules()
    {
        return [
            [['name', 'cat_id', 'description'], 'required'],
            [['name', 'alias'], 'string', 'max' => '255'],
            ['meta_description', 'string', 'max' => '200'],
            ['meta_keywords', 'string', 'max' => '250'],

            [
                [
                    'type_id', 'rating', 'rating_votes', 'selling',
                    'views', 'stars', 'noindex', 'fixed', 'published',
                ],
                'integer',
            ],

            [['cat_id', 'restrictions'], function ($attribute) {
                if (!is_array($this->$attribute)) {
                    $this->addError($attribute, 'Неверный формат данных, данные должны быть массивом.');
                }
            }],

            ['description', 'string', 'max' => '65535'],
            [['name', 'alias', 'meta_description', 'meta_keywords', 'description'], 'trim'],
            ['alias', TranslitFilter::className(), 'translitAttribute' => 'name'],

            [
                [
                    'meta_description', 'meta_keywords', 'included_in_price', 'not_included_in_price'
                ],
                'filter', 'filter' => function ($value) {
                return \yii\helpers\Html::encode($value);
            }],

            ['stars', 'in', 'range' => [0, 5]],

            // Default data
            [
                ['type_id', 'restrictions', 'rating', 'rating_votes', 'views', 'stars', 'selling'],
                'default', 'value' => 0,
            ],

            [['cat_id', 'restrictions'], 'default', 'value' => '[]'],
        ];
    }

    /**
     * @inheritdoc
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'alias' => 'Алиас',
            'cat_id' => 'Категории',
            'description' => 'Полное описание',
            'fixed' => 'Зафиксировать запись',
            'included_in_price' => 'В стоимость входит',
            'meta_description' => 'Описание (Description)',
            'meta_keywords' => 'Ключевые слова (Keywords)',
            'name' => 'Название тура',
            'noindex' => 'Запретить индексацию',
            'not_included_in_price' => 'В стоимость не входит',
            'published' => 'Публикация записи',
            'restrictions' => 'Ограничения',
            'stars' => 'Количество звёзд',
            'type_id' => 'Тип',
            'views' => 'Просмотры',
            'selling' => 'Тур онлайн',
        ];
    }

    /**
     * Tour prices
     * @return Array|common\models\ToursPrice
     */
    public function getPrices()
    {
        return $this->hasMany(TourPrices::className(), ['item_id' => 'id']);
    }

    /**
     * Tour prices for frontend
     * @return Array|common\models\ToursPrice
     */
    public function getFilterPrices()
    {
        return $this->hasMany(TourPrices::className(), ['item_id' => 'id'])
            ->andOnCondition('start_date >= :current_date AND published = :published', [
                ':current_date' => date(TourPrices::PROP_DATE_FORMAT),
                ':published' => TourPrices::PUBLISHED_ON
            ]);
    }

    /**
     * Tour programs
     * @return Array|common\models\TourPrograms
     */
    public function getPrograms() {
        return $this->hasMany(TourPrograms::className(), ['item_id' => 'id']);
    }

    /**
     * The cheapest
     * @return common\models\TourPrices
     */
    public function getPrice()
    {
        return $this->hasOne(TourPrices::className(), ['item_id' => 'id'])
            ->from(TourPrices::tableName() . ' p')
            ->andOnCondition(
                'p.start_date >= :current_date AND p.published = :published',
                [
                    ':current_date' => date(TourPrices::PROP_DATE_FORMAT),
                    ':published' => TourPrices::PUBLISHED_ON
                ]
            )
            ->addOrderBy(['p.base_price' => SORT_ASC]);
    }

    /**
     * Default minimum price
     * @return String
     */
    public function getDefaultPrice()
    {
        if ($this->price !== null) {
            return $this->price->price;
        }

        return '';
    }

    /**
     * @inheritdoc
     * @return boolean
     */
    public function beforeSave($insert)
    {
        if (is_array($this->cat_id)) {
            $this->cat_id = Json::encode($this->cat_id);
        }

        if (is_array($this->restrictions)) {
            $this->restrictions = Json::encode($this->restrictions);
        }

        return true;
    }

    /**
     * @inheritdoc
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        // Save dependency files to a new record
        if (count(Yii::$app->request->post('FilesTemp'))) {
            Files::filesTemp(Yii::$app->request->post('FilesTemp'), $this->id);
        }
    }

    /**
     * @inheritdoc
     */
    public function afterFind()
    {
        if (!is_null($this->cat_id) && !empty($this->cat_id)) {
            $this->cat_id = Json::decode($this->cat_id);
        }

        if (!is_null($this->restrictions) && !empty($this->restrictions)) {
            $this->restrictions = Json::decode($this->restrictions);
        }

        parent::afterFind();
    }

    /**
     * Prewiev Widget files
     * @return array
     */
    public function getPrewiewsWidget()
    {
        $files = [];
        foreach ($this->files as $item) {
            $files[] = $item->getPrewiews();
        }
        return $files;
    }

    /**
     * Default Images
     * @param  integer $index
     * @return [string]
     */
    public function getPathImage($index = 0)
    {
        if (count($this->files)) {
            return $this->files[$index]->getImageSize(self::DEFAULT_SIZE);
        }
        return '';
    }

    /**
     * Get Images size
     * @param  string $size
     * @param  integer $index
     * @return [string]
     */
    public function getImage($size = null, $index = 0)
    {
        if (count($this->files)) {
            return $this->files[$index]->getImageSize(is_null($size) ? self::DEFAULT_SIZE : $size);
        }
        return '';
    }

    /**
     * All related files
     * @return array
     */
    protected function getFiles()
    {
        return $this->hasMany(Files::className(), ['item_id' => 'id'])->andOnCondition([
            'module' => StringHelper::basename(self::className()),
        ])->select(['id', 'item_id', 'file', 'module', 'sizes']);
    }

    /**
     * Overall rating of the rating
     * @return integer
     */
    public function getRate() {
        if($this->rating) {
            return round(($this->rating / $this->rating_votes), 0, PHP_ROUND_HALF_UP);
        }
        return 0;
    }

    /**
     * Model category for display
     * @return  common\models\DataGr oup;
     */
    public function getCatModel() {
        if(is_array($this->cat_id) && count($this->cat_id) >= 1) {

frontend/controllers/CartController.php
<?php

/**
 * Cart products
 * @author Demid [Alexander Pilipenko] <webdemid@gmail.com>
 * @since 1.1
 */

namespace frontend\controllers;

use common\models\Tours;
use frontend\widgets\CartWidget;
use Yii;
use yii\web\Response;

/**
 * Site controller
 */
class CartController extends \frontend\components\FrontendController
{

    /**
     * Container for ajax replies
     * @var array
     */
    public $ajaxResponse = [
        'body' => false,
    ];

    /**
     * @inheritdoc
     * @return boolean
     */
    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            // Checking the signature for requests to the cart
            if (in_array($action->id, ['add', 'remove'])) {
                 if (!Yii::$app->request->isAjax) {
                    die('Access denied');
                }

                Yii::$app->response->format = Response::FORMAT_JSON;

                $id = Yii::$app->request->get('id', false);
                $sig = Yii::$app->request->get('sig', false);

                if ($id && $sig) {
                    if (!Yii::$app->cart->checkSignature($id, $sig)) {
                        $this->ajaxResponse['error'] = 'Ошибка! Неверная подпись.';
                    }
                } else {
                    $this->ajaxResponse['error'] = 'Access denied';
                }
            }

            return true;
        }
        return false;
    }

    /**
     * [actionIndex description]
     * @return String
     */
    public function actionIndex() {
        $cart = Yii::$app->cart->getRecord();
        $models = [];

        if(is_array($cart) && count($cart)) {
            $models = Tours::findAll(array_keys($cart));
        }
        return $this->render('index', ['models' => $models]);
    }

    /**
     * Add item to cart
     * @return String
     */
    public function actionAdd()
    {
        if (!array_key_exists('error', $this->ajaxResponse)) {
            $model = Tours::findOne((int) Yii::$app->request->get('id', 0));

            if (!is_null($model) && Yii::$app->cart->add($model->id, [])) {
                $this->ajaxResponse['count'] = Yii::$app->cart->count;
                if(Yii::$app->cart->count) {
                    $this->ajaxResponse['body'] = CartWidget::widget();

                    $cart_record = Yii::$app->cart->record;
                    $models = [];

                    if(is_array($cart_record) && count($cart_record)) {
                        $models = Tours::findAll(array_keys($cart_record));
                    }

                    $this->ajaxResponse['modal'] = $this->renderPartial('modal', [
                        'models' => $models
                    ]);
                }
            } else {
                $this->ajaxResponse['error'] = 'Не удалось найти запись в `DB`';
            }
        }

        return $this->ajaxResponse;
    }

    /**
     * Remove item from cart
     * @return [type] [description]
     */
    public function actionRemove()
    {
        if (!array_key_exists('error', $this->ajaxResponse)) {
            $id = (int) Yii::$app->request->get('id', 0);
            if($id && Yii::$app->cart->remove($id)) {
                $this->ajaxResponse['count'] = Yii::$app->cart->count;
                if(!$this->ajaxResponse['count']) {
                    $this->ajaxResponse['body'] = CartWidget::widget();
                }
            } else {
                $this->ajaxResponse['error'] = 'Не удалось удалить запись!';
            }
        }
        return $this->ajaxResponse;
    }
}

frontend/views/cart/index.php
<?php
use yii\helpers\Html;
?>
<section id="hero_2">
    <div class="intro_title animated fadeInDown">
        <h1>Корзина</h1>
        <div class="bs-wizard">
            <div class="col-xs-4 bs-wizard-step active">
                <div class="text-center bs-wizard-stepnum">Корзина</div>
                <div class="progress">
                    <div class="progress-bar"></div>
                </div>
                <a href="cart.html" class="bs-wizard-dot"></a>
            </div>
            <div class="col-xs-4 bs-wizard-step disabled">
                <div class="text-center bs-wizard-stepnum">Оформление</div>
                <div class="progress">
                    <div class="progress-bar"></div>
                </div>
                <a href="ordering.html" class="bs-wizard-dot"></a>
            </div>
            <div class="col-xs-4 bs-wizard-step disabled">
                <div class="text-center bs-wizard-stepnum">Готово!</div>
                <div class="progress">
                    <div class="progress-bar"></div>
                </div>
                <a href="confirmation.html" class="bs-wizard-dot"></a>
            </div>
        </div>
        <!-- End bs-wizard -->
    </div>
    <!-- End intro-title -->
</section>
<!-- End Section hero_2 -->
<main class="white_bg">
    <div class="container margin_60">
        <div class="row">
            <div class="col-md-12">
            <? if(count($models)): ?>
                <table class="table table-striped cart-list add_bottom_30">
                    <thead>
                        <tr>
                            <th width="70%">Туры онлайн</th>
                            <th>Стоимость от</th>
                            <th class="text-center">Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                    <? foreach($models as $item): ?>
                        <tr data-cart-id="<?= $item->id ?>">
                            <td>
                                <? if($item->image): ?>
                                <div class="thumb_cart" style="background-image: url('<?= $item->getImage('100x100') ?>')"></div>
                                <? else: ?>
                                <div class="thumb_cart"></div>
                                <? endif; ?>
                                <span class="item_cart">
                                    <a href="<?= $item->link ?>" class="item_cart-name">
                                        <?= $item->name ?>
                                    </a>
                                    <? if($item->catModel !== null): ?>
                                    <div class="item_cart-cat">
                                        <i class="<?= $item->catModel->icon_css ?>"></i>
                                        <span><?= $item->catModel->name ?></span>
                                    </div>
                                    <? endif; ?>
                                </span>
                            </td>
                            <td>
                                <strong><?= $item->defaultPrice ?></strong>
                            </td>
                            <td class="options text-center">
                                <a href="#" onclick="return removeItemCart('<?= Yii::$app->cart->generateSignature($item->id) ?>', <?= $item->id ?>, this);" title="Удалить из корзины"><i class=" icon-trash"></i></a>
                                <?/*<a href="#" onclick="return false" title="Обновить"><i class="icon-ccw-2"></i></a>*/?>
                            </td>
                        </tr>
                    <? endforeach; ?>
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-sm-6">
                        <a class="btn_1_outline mr-5" href="/tours?sort=online">
                            <i class="icon-right"></i> Вернуться в каталог
                        </a>
                    </div>
                    <div class="col-sm-6 text-right">
                        <a class="btn_1" href="<?= Yii::$app->cart->linkOrdering ?>">
                            Оформить заказ
                            <i class="icon-left"></i>
                        </a>
                    </div>
                </div>
            <? else: ?>
            <div class="text-center">
                <h4>Ваша корзина пустая, Заполните корзину онлайн турами,<br> чтобы оформить заказ.</h4>
                <a class="btn_1_outline mt-15" href="/tours?sort=online">
                    <i class="icon-right"></i> Перейти в каталог туров
                </a>
            </div>
            <? endif; ?>
            </div>
            <?/*<!-- End col-md-8 -->
            <aside class="col-md-4">
                <div class="box_style_1">
                    <h3 class="inner">- Резюме -</h3>
                    <table class="table table_summary">
                        <tbody>
                            <tr>
                                <td>
                                    Взрослые
                                </td>
                                <td class="text-right">
                                    2
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Дети
                                </td>
                                <td class="text-right">
                                    0
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Джип-тур
                                </td>
                                <td class="text-right">
                                    $34
                                </td>
                            </tr>
                            <tr class="total">
                                <td>
                                    Итого
                                </td>
                                <td class="text-right">
                                    $104
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <a class="btn_full" href="ordering.html">Оформить</a>
                    <a class="btn_full_outline" href="/tours?sort=online"><i class="icon-right"></i> Вернуться к поиску</a>
                </div>
            </aside>
            <!-- End aside -->*/?>
        </div>
        <!--End row -->
    </div>
    <!--End container -->
</main>
<!-- End main -->

frontend/views/cart/modal.php
<div class="modal-header">
    <h5 class="modal-title">Ваша корзина (<?= Yii::$app->cart->count ?>)</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Закрыть" title="Закрыть">
        <i class="icon-cancel-2" aria-hidden="true"></i>
    </button>
</div>
<div class="modal-body">
    <? if(count($models)): ?>
    <table class="table cart-list add_bottom_30">
        <thead>
            <tr>
                <th width="70%">Туры онлайн</th>
                <th class="text-center">Стоимость от</th>
                <th class="text-center">Действия</th>
            </tr>
        </thead>
        <tbody>
        <? foreach($models as $item): ?>
            <tr data-cart-id="<?= $item->id ?>">
                <td>
                    <? if($item->image): ?>
                    <div class="thumb_cart" style="background-image: url('<?= $item->getImage('100x100') ?>')"></div>
                    <? else: ?>
                    <div class="thumb_cart"></div>
                    <? endif; ?>
                    <span class="item_cart">
                        <a href="<?= $item->link ?>" class="item_cart-name">
                            <?= $item->name ?>
                        </a>
                        <? if($item->catModel !== null): ?>
                        <div class="item_cart-cat">
                            <i class="<?= $item->catModel->icon_css ?>"></i>
                            <span><?= $item->catModel->name ?></span>
                        </div>
                        <? endif; ?>
                    </span>
                </td>
                <td class="text-center">
                    <strong><?= $item->defaultPrice ?></strong>
                </td>
                <td class="options text-center">
                    <a href="#" onclick="return removeItemCart('<?= Yii::$app->cart->generateSignature($item->id) ?>', <?= $item->id ?>, this);" title="Удалить из корзины"><i class=" icon-trash"></i></a>
                    <?/*<a href="#" onclick="return false" title="Обновить"><i class="icon-ccw-2"></i></a>*/?>
                </td>
            </tr>
        <? endforeach; ?>
        </tbody>
    </table>
    <? else: ?>
    <div class="text-center">
        Ваша корзина пустая
    </div>
    <? endif; ?>
</div>
<div class="modal-footer">
    <a href="#" data-dismiss="modal" class="btn_1 outline mr-5 btn_xs-block">
        <i class="icon-right"></i>
        Вернуться в каталог
    </a>
    <a href="<?= Yii::$app->cart->linkOrdering ?>" class="btn_1 btn_xs-block">
        Оформить заказ
        <i class="icon-left"></i>
    </a>
</div>